export const t = {
  home: {
    allTracks: "Todas as Músicas",
    playAll: "Tocar Todas",
    tracks: (n: number) => `${n} faixa${n !== 1 ? "s" : ""}`,
  },
  downloads: {
    title: "Downloads",
    quality: (q: string) => `${q} AAC`,
    fromYoutube: "Do YouTube → salva no dispositivo",
    pasteUrl: "Cole a URL do YouTube...",
    folder: "Pasta",
    noFolder: "Sem pasta",
    download: "Baixar",
    queue: "Fila",
    saved: "salvo",
    failed: "falhou",
    extracting: "extraindo…",
    saving: "salvando…",
    noAudioFiles: "Nenhum arquivo de áudio",
    supportedFormats: "MP3, M4A, FLAC, WAV, OGG suportados.",
    imported: (n: number) => `${n} faixa${n !== 1 ? "s" : ""} importada${n !== 1 ? "s" : ""}`,
    importFromDevice: "Importar do Dispositivo",
    chooseFiles: "Escolher Arquivos",
    importing: "Importando…",
    dropToImport: "Solte para importar",
    dragAndDrop: "Arraste arquivos de áudio aqui",
    savedToDevice: "MP3, M4A, FLAC, WAV, OGG — salvos no dispositivo",
  },
  folder: {
    notFound: "Pasta não encontrada",
    playlist: "Playlist",
    rename: "Renomear Pasta",
    delete: "Excluir Pasta",
    playFolder: "Tocar Pasta",
    tracks: (n: number) => `${n} faixa${n !== 1 ? "s" : ""}`,
    renameTitle: "Renomear Pasta",
    cancel: "Cancelar",
    save: "Salvar",
    deleteTitle: "Excluir Pasta",
    deleteConfirm: (name: string) => `Excluir pasta <strong>"${name}"</strong>? As faixas serão movidas para a Biblioteca.`,
    deleteBtn: "Excluir",
  },
  settings: {
    title: "Configurações",
    saved: "Configurações salvas",
    qualitySet: (v: string) => `Qualidade definida para ${v}`,
    downloadQuality: "Qualidade de Download",
    qualityDesc: "Taxa do AAC (.m4a) para downloads do YouTube. Maior = melhor som, arquivo maior.",
    qualities: [
      { label: "64 kbps", desc: "Pequeno", size: "~1,4 MB / min" },
      { label: "128 kbps", desc: "Equilibrado", size: "~2,8 MB / min" },
      { label: "192 kbps", desc: "Bom", size: "~4,3 MB / min" },
      { label: "256 kbps", desc: "Alto", size: "~5,8 MB / min" },
    ],
    youtubeCookies: "Cookies do YouTube",
    cookiesDesc: "Necessário para bypassar a detecção de bot do YouTube. Exporte do navegador com a extensão \"Get cookies.txt LOCALLY\" e cole abaixo.",
    cookiesPlaceholder: "Cole seus cookies do YouTube aqui (formato Netscape)...",
    cookiesSecure: "Seus cookies são armazenados localmente e nunca compartilhados.",
    changesNote: "Alterações valem apenas para novos downloads. Faixas existentes não são afetadas.",
    noFolder: "Sem pasta",
  },
  notFound: {
    title: "404 Página Não Encontrada",
    desc: "Esqueceu de adicionar a página ao roteador?",
  },
  sidebar: {
    sanctuary: "Sanctuary",
    library: "Biblioteca",
    downloads: "Downloads",
    settings: "Configurações",
    playlists: "Playlists",
    folderCreated: "Pasta criada",
    folderAdded: (name: string) => `"${name}" adicionada à sua biblioteca`,
    error: "Erro",
    failedCreate: "Falha ao criar pasta",
    newFolder: "Nova Pasta",
    folderName: "Nome da pasta...",
    cancel: "Cancelar",
    create: "Criar",
    noFolders: "Nenhuma pasta ainda",
  },
  player: {
    noArt: "Sem Arte",
  },
  mobileNav: {
    library: "Biblioteca",
    downloads: "Downloads",
    settings: "Configurações",
  },
  trackList: {
    noTracks: "Nenhuma faixa ainda",
    noTracksDesc: "Baixe músicas do YouTube — elas serão salvas diretamente no seu dispositivo.",
    editInfo: "Editar Info",
    moveToFolder: "Mover para Pasta",
    noFolder: "Sem Pasta",
    deleteTrack: "Excluir Faixa",
    colNum: "#",
    colTitle: "Título",
    colArtist: "Artista",
    colAdded: "Adicionada",
    colSize: "Tamanho",
    editTitle: "Editar Informação da Faixa",
    title: "Título",
    artist: "Artista",
    cancel: "Cancelar",
    saveChanges: "Salvar Alterações",
  },
};
